insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gimca-2-2026-11-08',
  'gimca-2',
  null,
  'encontro_regular',
  '2026-11-08',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Encontro mensal',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gimca-2-2026-12-06',
  'gimca-2',
  null,
  'encontro_regular',
  '2026-12-06',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Último encontro do ano',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'afetividade-jovens-2026-02-21',
  null,
  '6f6ac7f4-7c5c-4a79-9f9d-2b2fd3d0a101',
  'encontro_regular',
  '2026-02-21',
  '2026-02-22',
  '',
  'Dois dias',
  'CMV',
  'Retiro afetividade Jovens',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'jeshua-2026-03-20',
  null,
  'd0c22f65-2453-4b5f-8300-f91f1dcff102',
  'encontro_regular',
  '2026-03-20',
  '2026-03-22',
  '',
  'Três dias',
  'CMV',
  'Jeshuá',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'jeshua-2026-09-25',
  null,
  'd0c22f65-2453-4b5f-8300-f91f1dcff102',
  'encontro_regular',
  '2026-09-25',
  '2026-09-27',
  '',
  'Três dias',
  'CMV',
  'Jeshuá',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'grand-prix-formula-1-2026-05-15',
  null,
  '3b33e0bb-2cb8-4d31-bf95-f6c2cb4ab103',
  'encontro_regular',
  '2026-05-15',
  '2026-05-17',
  '',
  'Três dias',
  'CMV',
  'Grand Prix Formula 1',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gimvi-criancas-2026-02-08',
  'gimvi-criancas',
  null,
  'encontro_regular',
  '2026-02-08',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Primeiro encontro mensal',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gimvi-criancas-2026-03-08',
  'gimvi-criancas',
  null,
  'encontro_regular',
  '2026-03-08',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Segundo encontro mensal',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gimvi-criancas-2026-04-12',
  'gimvi-criancas',
  null,
  'encontro_regular',
  '2026-04-12',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Terceiro encontro mensal',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gimvi-criancas-2026-05-17',
  'gimvi-criancas',
  null,
  'encontro_regular',
  '2026-05-17',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Quarto encontro mensal',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gimvi-criancas-2026-06-07',
  'gimvi-criancas',
  null,
  'encontro_regular',
  '2026-06-07',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Quinto encontro mensal',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gimvi-criancas-2026-08-02',
  'gimvi-criancas',
  null,
  'encontro_regular',
  '2026-08-02',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Sexto encontro mensal',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gimvi-criancas-2026-09-13',
  'gimvi-criancas',
  null,
  'encontro_regular',
  '2026-09-13',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Sétimo encontro mensal',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gimvi-criancas-2026-10-04',
  'gimvi-criancas',
  null,
  'encontro_regular',
  '2026-10-04',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Oitavo encontro mensal',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gimvi-criancas-2026-11-08',
  'gimvi-criancas',
  null,
  'encontro_regular',
  '2026-11-08',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Nono encontro mensal',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gimvi-criancas-2026-12-06',
  'gimvi-criancas',
  null,
  'encontro_regular',
  '2026-12-06',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Último encontro do ano',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'cana-2026-04-18',
  null,
  '0f0aa7de-a88e-4761-8f57-b7a211c9d104',
  'encontro_regular',
  '2026-04-18',
  '2026-04-19',
  '',
  'Dois dias',
  'CMV',
  'CANÁ',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'areia-ou-rocha-2026-08-15',
  null,
  '1c250f5d-83f9-4473-b94a-ef6dfeef3105',
  'encontro_regular',
  '2026-08-15',
  '2026-08-16',
  '',
  'Dois dias',
  'CMV',
  'AREIA OU  ROCHA',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'afetividade-casais-2026-08-29',
  null,
  'fb334ac3-53d1-456a-8108-3d526511f106',
  'encontro_regular',
  '2026-08-29',
  '2026-08-30',
  '',
  'Dois dias',
  'CMV',
  'AFETIVIDADE  CASAIS',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gimvi-jovens-2026-03-01',
  'gimvi-jovens',
  null,
  'evento_especial',
  '2026-03-01',
  null,
  '',
  '15h00 - 18h30',
  'CMV Galpão',
  'Convocação Grand Prix',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gimvi-jovens-2026-03-08',
  'gimvi-jovens',
  null,
  'encontro_regular',
  '2026-03-08',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Encontro para todos os grupos',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gam-2026-02-08',
  'gam',
  null,
  'encontro_regular',
  '2026-02-08',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Primeiro encontro mensal',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gam-2026-03-08',
  'gam',
  null,
  'encontro_regular',
  '2026-03-08',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Encontro com todos os grupos',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gam-2026-04-12',
  'gam',
  null,
  'encontro_regular',
  '2026-04-12',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Terceiro encontro mensal',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gam-2026-05-17',
  'gam',
  null,
  'encontro_regular',
  '2026-05-17',
  null,
  '',
  '7h00 - 18h00',
  'Partida CMV',
  'Passeio',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;
