insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gam-2026-06-07',
  'gam',
  null,
  'encontro_regular',
  '2026-06-07',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Quarto encontro mensal',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gam-2026-07-04',
  'gam',
  null,
  'evento_especial',
  '2026-07-04',
  '2026-07-05',
  '',
  'Dois dias',
  'Paróquia São Sebastião',
  'Arraiá do Betânia',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gam-2026-08-02',
  'gam',
  null,
  'encontro_regular',
  '2026-08-02',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Quinto encontro mensal',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gam-2026-09-06',
  null,
  '5c0e6f63-3298-4f25-b754-4d3c88f7e201',
  'encontro_regular',
  '2026-09-06',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Aniversário da CMV. Encontro com a presidente da Comunidade Missionária de Villaregia, Briseida',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gam-2026-10-04',
  'gam',
  null,
  'encontro_regular',
  '2026-10-04',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Sétimo encontro mensal',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gam-2026-11-08',
  'gam',
  null,
  'encontro_regular',
  '2026-11-08',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Oitavo encontro mensal',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gam-2026-12-06',
  'gam',
  null,
  'encontro_regular',
  '2026-12-06',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Último encontro do ano',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'emaus-2026-11-14',
  null,
  '727bb9b1-3d38-49fb-a184-7f116f954107',
  'encontro_regular',
  '2026-11-14',
  '2026-11-15',
  '',
  'Dois dias',
  'CMV',
  'Emaús',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gimca-2-2026-04-12',
  'gimca-2',
  null,
  'encontro_regular',
  '2026-04-12',
  null,
  '',
  '9h00 - 16h00',
  'CMV',
  'Encontro mensal',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;

insert into public.encontros (
  id,
  grupo_id,
  evento_id,
  tipo,
  data_inicio,
  data_fim,
  data_legivel,
  horario,
  local,
  titulo,
  descricao,
  visibilidade,
  nivel,
  mostrar_no_anual
)
values (
  'gimca-2-2026-06-13',
  'gimca-2',
  null,
  'encontro_regular',
  '2026-06-13',
  null,
  '',
  '18h00 - 21h00',
  'CMV',
  'Encontro a noite',
  '',
  'publico',
  'evento',
  true
)
on conflict (id) do update set
  grupo_id = excluded.grupo_id,
  evento_id = excluded.evento_id,
  tipo = excluded.tipo,
  data_inicio = excluded.data_inicio,
  data_fim = excluded.data_fim,
  data_legivel = excluded.data_legivel,
  horario = excluded.horario,
  local = excluded.local,
  titulo = excluded.titulo,
  descricao = excluded.descricao,
  visibilidade = excluded.visibilidade,
  nivel = excluded.nivel,
  mostrar_no_anual = excluded.mostrar_no_anual;
